config/routes.rb
Rails.application.routes.draw do
  get 'college/coll_list'

  get 'college/coll_add'

  get 'college/coll_edit'

  get 'college/coll_delete'

  get 'college/coll_details'

  get 'practice/add'
  match "practice/add", to: "practice#add", via: "post"
  
  get 'practice/entry'
  get 'upload/edu_dept'
  get 'upload/dept_list'
  get 'upload/forms'
  
  match 'upload/dept_add', to: "upload#dept_add", via: "post"  
  match "upload/create", to: "upload#create", via: "post"

end

app/models/college_mst.rb
class CollegeMst < ActiveRecord::Base
end

app/models/dept.rb
class Dept < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/college_controller.rb
class CollegeController < ApplicationController
  def coll_list
  end

  def coll_add
  end

  def coll_edit
  end

  def coll_delete
  end

  def coll_details
  end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def add
    @person = Person.new(user_params)
    @person.save
  end
   private

  def user_params
    params.require(:person).permit(:first_name, :last_name, :biography, :admin)
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  layout 'master'
  
  def edu_dept
  end
  
  def
  
  def create
    name = params[:upload][:file].original_filename
    directory = "/public/excel"
    root = Rails.root
    path = file = File.join(Rails.root, directory, name)
    File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }
    flash[:notice] = "File uploaded"
    redirect_to "/upload/edu_dept"
  end
  
  def dept_list
  end
  
  def dept_add
    @dept_det = Dept.new(params.require(:department).permit(:dept_id, :dept_name))
    @dept_det.save  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/college_helper.rb
module CollegeHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/college/coll_add.html.erb
<h1>College#coll_add</h1>
<p>Finddddddddddd me in app/views/college/coll_add.html.erb</p>

app/views/college/coll_delete.html.erb
<h1>College#coll_delete</h1>
<p>Find me in app/views/college/coll_delete.html.erb</p>

app/views/college/coll_details.html.erb
<h1>College#coll_details</h1>
<p>Find me in app/views/college/coll_details.html.erb</p>

app/views/college/coll_edit.html.erb
<h1>College#coll_edit</h1>
<p>Find me in app/views/college/coll_edit.html.erb</p>

app/views/college/coll_list.html.erb
<h1>College#coll_list</h1>
<p>Find meeeeeeeeeeeee in app/views/college/coll_list.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyAppTryOne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/master.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>R2R</title>
		<!-- Base Css Files -->
		<link href="/assets/libs/jqueryui/ui-lightness/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
		<link href="/assets/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
		<link href="/assets/libs/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
		<link href="/assets/libs/fontello/css/fontello.css" rel="stylesheet" />
		<link href="/assets/libs/animate-css/animate.min.css" rel="stylesheet" />
		<link href="/assets/libs/nifty-modal/css/component.css" rel="stylesheet" />
		<link href="/assets/libs/magnific-popup/magnific-popup.css" rel="stylesheet" />
		<link href="/assets/libs/pace/pace.css" rel="stylesheet" />
		<link href="/assets/libs/sortable/sortable-theme-bootstrap.css" rel="stylesheet" />
		<link href="/assets/libs/bootstrap-datepicker/css/datepicker.css" rel="stylesheet" />
		<link href="/assets/libs/jquery-icheck/skins/all.css" rel="stylesheet" />
		<!-- Code Highlighter for Demo -->
		<link href="/assets/libs/prettify/github.css" rel="stylesheet" />
		<!-- Extra CSS Libraries Start -->
		<link href="/assets/libs/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" type="text/css" />
		<link href="/assets/libs/summernote/summernote.css" rel="stylesheet" type="text/css" />
		<link href="/assets/css/style.css" rel="stylesheet" type="text/css" />
		<!-- Extra CSS Libraries End -->
		<!--
		// one restocs
		-->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
		<link rel="shortcut icon" href="/assets/img/favicon.ico">
		<!--
		// breadcrumb two add icons link for apple, andr. later
		-->
	</head>
	<body class="fixed-left">
		<!-- Begin page -->
		<div id="wrapper">
			<!-- Top Bar Start -->
			<div class="topbar">
				<div class="topbar-left">
					<div class="logo">
						<center>
							<h3><a href="#" style="color: white !important;">My App</a></h2>
						</center>
					</div>
					<!--
					mobile resize button to be added <button></button>
					-->
				</div>
				<!-- Button view to collapse sidebar menu -->
				<div class="navbar navbar-default" role="navigation">
					<div class="container">
						<div class="navbar-collapse2">
							<ul class="nav navbar-nav navbar-right top-navbar">
								<li class="dropdown topbar-profile">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="rounded-image topbar-profile-image"><img src="/assets/img/user.png"></span><strong>Gopi</strong> <i class="fa fa-caret-down"></i></a>
									<ul class="dropdown-menu">
										<li>
											<a href="#">Account Setting</a>
										</li>
										<li class="divider"></li>
										<li>
											<a class="md-trigger" data-modal="logout-modal"><i class="icon-logout-1"></i> Logout</a>
										</li>
									</ul>
								</li>
							</ul>
						</div>
						<!--/.nav-collapse -->
					</div>
				</div>
			</div>
			<!-- Top Bar End -->
			<!-- Left Sidebar Start -->
			<div class="left side-menu">
				<div class="sidebar-inner slimscrollleft">

					<div class="clearfix">
						&nbsp;
					</div>
					<!--- Profile -->
					<div class="profile-info">
						<div class="col-xs-4">
							<a href="profile.html" class="rounded-image"><img src="/assets/img/user.png"></a>
						</div>
						<div class="col-xs-8">
							<div class="profile-text">
								Welcome <b>Gopi</b>
							</div>
						</div>
					</div>
					<!--- Divider -->
					<div class="clearfix"></div>
					<hr class="divider" />
					<div class="clearfix"></div>
					<!--- Divider -->
					<div id="sidebar-menu">
						<ul>
							<li class='has_sub'>
								<a href='javascript:void(0);'><i class='icon-home-3'></i><span>Menu</span> <span class="pull-right"><i class="fa fa-plus"></i></span></a>
								<ul>
									<li>
										<a href='forms.html'><span>Menu 1</span></a>
									</li>
									<li>
										<a href='advanced-forms.html' class='active'><span>Menu 2</span></a>
									</li>
									<li>
										<a href='form-wizard.html'><span>Menu 3</span></a>
									</li>
									<li>
										<a href='form-validation.html'><span>Menu 4</span></a>
									</li>
								</ul>
							</li>
							<li class='has_sub'>
								<a href='javascript:void(0);'><i class='fa fa-sign-out'></i><span>Logout</span><span class="pull-right"></span></a>
							</li>

						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="clearfix"></div>
					<div class="clearfix"></div>
					<br>
					<br>
					<br>
				</div>
			</div>
			<!-- Left Sidebar End -->
			<!-- Start right content -->
<div class="content-page">
	<!-- ============================================================== -->
	<!-- Start Content here -->
	<!-- ============================================================== -->
	<div class="content">
		<%= yield %>
			<!-- Footer Start -->
			<footer>
				My App &copy; 2015. Designed by My_App Pvt.Ltd.
				<div class="footer-links pull-right">
					<a href="#">About</a><a href="#">Features</a><a href="#">Clients</a><a href="#">Terms of Service</a><a href="#">Privacy Policy</a><a href="#">Help</a><a href="#">Contact Us</a>
				</div>
			</footer>
			<!-- Footer End -->
		</div>
		<!-- ============================================================== -->
		<!-- End content here -->
		<!-- ============================================================== -->
		</div>
		<!-- End right content -->
		</div>
		<!-- End of page -->
		<!-- the overlay modal element -->
		<div class="md-overlay"></div>
		<!-- End of eoverlay modal -->
		<script>
			var resizefunc = [];
		</script>
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="/assets/libs/jquery/jquery-1.11.1.min.js"></script>
		<script src="/assets/libs/bootstrap/js/bootstrap.min.js"></script>
		<script src="/assets/libs/jqueryui/jquery-ui-1.10.4.custom.min.js"></script>
		<script src="/assets/libs/jquery-ui-touch/jquery.ui.touch-punch.min.js"></script>
		<script src="/assets/libs/jquery-animate-numbers/jquery.animateNumbers.js"></script>
		<script src="/assets/libs/fastclick/fastclick.js"></script>
		<script src="/assets/libs/jquery-blockui/jquery.blockUI.js"></script>
		<script src="/assets/libs/bootstrap-bootbox/bootbox.min.js"></script>
		<script src="/assets/libs/jquery-slimscroll/jquery.slimscroll.js"></script>
		<script src="/assets/libs/jquery-sparkline/jquery-sparkline.js"></script>
		<script src="/assets/libs/nifty-modal/js/classie.js"></script>
		<script src="/assets/libs/nifty-modal/js/modalEffects.js"></script>
		<script src="/assets/libs/sortable/sortable.min.js"></script>
		<script src="/assets/libs/bootstrap-fileinput/bootstrap.file-input.js"></script>
		<script src="/assets/libs/bootstrap-select/bootstrap-select.min.js"></script>
		<script src="/assets/libs/bootstrap-select2/select2.min.js"></script>
		<script src="/assets/libs/magnific-popup/jquery.magnific-popup.min.js"></script>
		<script src="/assets/libs/pace/pace.min.js"></script>
		<script src="/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="/assets/libs/jquery-icheck/icheck.min.js"></script>

		<!-- Demo Specific JS Libraries -->
		<script src="/assets/libs/prettify/prettify.js"></script>
		<script src="/assets/js/init.js"></script>
		
		<!-- Page Specific JS Libraries -->
		<script src="/assets/libs/bootstrap-select/bootstrap-select.min.js"></script>
		<script src="/assets/libs/bootstrap-inputmask/inputmask.js"></script>
		<script src="/assets/libs/summernote/summernote.js"></script>
		<script src="/assets/js/pages/forms.js"></script>
	</body>
</html>

app/views/practice/add.html.erb
<h1>Practice#add</h1>
<p>Find me in app/views/practice/add.html.erb</p>

app/views/practice/entry.html.erb
<%= form_for :person, url: practice_add_path(:person) do |f| -%>
  First name: <%= f.text_field :first_name %><br />
  Last name : <%= f.text_field :last_name %><br />
  Biography : <%= f.text_area :biography %><br />
  Admin?    : <%= f.check_box :admin %><br />
  <%= f.submit %>
<% end -%>

app/views/upload/dept_list.html.erb
<h1>Add Department</h1>
<p>
	In this page you can view the departments available and add a new department
</p>
<%= form_for :department, url: upload_dept_add_path(:department) do |f| -%>
<form role="form">
	<div class="form-group">
		<label>Department ID</label>
		<%= f.text_field :dept_id, :class =>"form-control", :id => "dept", :placeholder => "Enter department" %>
	</div>
	<div class="form-group">
		<label>Department</label>
		<%= f.text_field :dept_name, :class =>"form-control", :id => "dept", :placeholder => "Enter department" %>
	</div>
	<br />
	<%= f.submit "Add" %>
</form>
<% end -%>

app/views/upload/edu_dept.html.erb
<h1>File Uploading</h1>
<p>In this page you can upload files and it is saved in rails root directory</p>
<%= form_tag '/upload/create', { :multipart => true } do -%>
    <p>
    <%= file_field_tag 'upload[file]' %>
    </p>
    <p>
    	<%= submit_tag "Upload" %>
    </p>
<% end -%>

app/views/upload/forms.html.erb
<!-- Page Heading Start -->
<div class="page-heading">
	<h1><i class='fa fa-check'></i> Forms</h1>
</div>
<!-- Page Heading End-->

<div class="widget">
	<div class="widget-header transparent">
		<h2><strong>Form</strong> Element</h2>

	</div>
	<div class="widget-content padding">
		<form class="form-horizontal" role="form">
			<div class="form-group">
				<label for="input-text" class="col-sm-2 control-label">Input text</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="input-text" placeholder="Input text">
				</div>
			</div>
			<div class="form-group">
				<label for="input-text-help" class="col-sm-2 control-label">Input text with help</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="input-text-help" placeholder="Input text placeholder">
					<p class="help-block">
						Example block-level help text here.
					</p>
				</div>
			</div>
			<div class="form-group">
				<label for="inputPassword" class="col-sm-2 control-label">Password</label>
				<div class="col-sm-10">
					<input type="password" class="form-control" id="inputPassword" placeholder="Password">
				</div>
			</div>
			<div class="form-group">
				<label for="input-text-disabled" class="col-sm-2 control-label">Disabled</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="input-text-disabled" placeholder="Input text" disabled>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Static Control</label>
				<div class="col-sm-10">
					<p class="form-control-static">
						email@example.com
					</p>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Radio</label>
				<div class="col-sm-10">
					<div class="radio iradio">
						<label>
							<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
							Option one is this and that&mdash;be sure to include why it's great </label>
					</div>
					<div class="radio iradio">
						<label>
							<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
							Option two can be something else and selecting it will deselect option one </label>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Checkbox</label>
				<div class="col-sm-10">
					<div class="checkbox">
						<label>
							<input type="checkbox" value="">
							Option one is this and that&mdash;be sure to include why it's great </label>
					</div>
					<div class="checkbox">
						<label>
							<input type="checkbox" value="">
							Option one is this and that&mdash;be sure to include why it's great </label>
					</div>
					<div class="checkbox">
						<label>
							<input type="checkbox" value="">
							Option one is this and that&mdash;be sure to include why it's great </label>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Inline Checkbox</label>
				<div class="col-sm-10">
					<label class="checkbox-inline icheckbox">
						<input type="checkbox" id="inlineCheckbox1" value="option1">
						1 </label>
					<label class="checkbox-inline icheckbox">
						<input type="checkbox" id="inlineCheckbox2" value="option2">
						2 </label>
					<label class="checkbox-inline icheckbox">
						<input type="checkbox" id="inlineCheckbox3" value="option3">
						3 </label>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Select</label>
				<div class="col-sm-10">
					<select class="form-control">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label"></label>
				<div class="col-sm-10">
					<select multiple class="form-control">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
			</div>

			<div class="form-group">
				<label class="col-sm-2 control-label">Custom Select</label>
				<div class="col-sm-10">
					<select class="form-control selectpicker">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
			</div>

			<div class="form-group">
				<label class="col-sm-2 control-label">File Input</label>
				<div class="col-sm-10">
					<input type="file" class="btn btn-default" title="Select files">
				</div>
			</div>

			<div class="form-group">
				<label class="col-sm-2 control-label">Datepicker</label>
				<div class="col-sm-3">
					<input type="text" class="form-control datepicker-input">
				</div>
			</div>

			<div class="form-group">
				<label class="col-sm-2 control-label">WYSWYG</label>
				<div class="col-sm-10">
					<textarea class="summernote"></textarea>
				</div>
			</div>

			<div class="form-group">
				<label class="col-sm-2 control-label">&nbsp;</label>
				<div class="col-sm-10">
					<button type="submit" class="btn btn-default btn-lg">
						Submit
					</button>
					&nbsp;&nbsp;
					<button type="submit" class="btn btn-default btn-lg">
						Sign in
					</button>

				</div>
			</div>

		</form>
	</div>

</div>